In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path
import sqlalchemy as sa

# Desactivar la notacion cientifica
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [42]:
# Configurar ruta relativa
ruta_datos = Path('..') / 'datos' / 'brutos' / 'ecommerce.db'

# Crear engine de SQLAlchemy
engine = sa.create_engine(f'sqlite:///{ruta_datos}')

# Verificar la conexión y tablas disponibles
inspector = sa.inspect(engine)
tablas = inspector.get_table_names()
print(f"Tablas disponibles: {tablas}")

# También puedes probar la conexión así:
with engine.connect() as conn:
    resultado = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table';"))
    print("Tablas:", resultado.fetchall())

Tablas disponibles: ['2019-Dec', '2019-Nov', '2019-Oct', '2020-Feb', '2020-Jan']
Tablas: [('2019-Oct',), ('2019-Nov',), ('2019-Dec',), ('2020-Jan',), ('2020-Feb',)]

In [43]:
oct = pd.read_sql('2019-Oct', con=engine)
nov = pd.read_sql('2019-Nov', con=engine)
dic = pd.read_sql('2019-Dec', con=engine)
ene = pd.read_sql('2020-Jan', con=engine)
feb = pd.read_sql('2020-Feb', con=engine)

In [44]:
print(oct.shape, nov.shape, dic.shape, ene.shape, feb.shape)

(407925, 10) (462833, 10) (351304, 10) (443224, 10) (429790, 10)

In [45]:
print(oct.columns)
print(nov.columns)
print(dic.columns)
print(ene.columns)
print(feb.columns)

Index(['index', 'event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')
Index(['index', 'event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')
Index(['index', 'event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')
Index(['index', 'event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')
Index(['index', 'event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [46]:
df = pd.concat([oct, nov, dic, ene, feb], ignore_index=True, axis=0)
df

,index,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,68,2019-10-01 00:01:46 UTC,view,5843665,1487580005092295511,NaN,f.o.x,9.44,462033176,a18e0999-61a1-4218-8f8f-61ec1d375361
1,72,2019-10-01 00:01:55 UTC,cart,5868461,1487580013069861041,NaN,italwax,3.57,514753614,e2fecb2d-22d0-df2c-c661-15da44b3ccf1
2,95,2019-10-01 00:02:50 UTC,view,5877456,1487580006300255120,NaN,jessnail,122.22,527418424,86e77869-afbc-4dff-9aa2-6b7dd8c90770
3,122,2019-10-01 00:03:41 UTC,view,5649270,1487580013749338323,NaN,concept,6.19,555448072,b5f72ceb-0730-44de-a932-d16db62390df
4,124,2019-10-01 00:03:44 UTC,view,18082,1487580005411062629,NaN,cnd,16.03,552006247,2d8f304b-de45-4e59-8f40-50c603843fe5
...,...,...,...,...,...,...,...,...,...,...
2095071,4156660,2020-02-29 23:58:49 UTC,cart,5815662,1487580006317032337,NaN,NaN,0.92,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095072,4156663,2020-02-29 23:58:57 UTC,view,5815665,1487580006317032337,NaN,NaN,0.59,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095073,4156668,2020-02-29 23:59:05 UTC,cart,5815665,1487580006317032337,NaN,NaN,0.59,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095074,4156675,2020-02-29 23:59:28 UTC,view,5817692,1487580010872045658,NaN,NaN,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d
2095075,4156680,2020-02-29 23:59:54 UTC,view,5716351,1487580010872045658,NaN,irisk,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2095076 entries, 0 to 2095075
Data columns (total 10 columns):
 #   Column         Dtype
---  ------         -----
 0   index          int64
 1   event_time     str
 2   event_type     str
 3   product_id     int64
 4   category_id    int64
 5   category_code  str
 6   brand          str
 7   price          float64
 8   user_id        int64
 9   user_session   str
dtypes: float64(1), int64(4), str(5)
memory usage: 159.8 MB

In [48]:
df.head(3)

,index,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,68,2019-10-01 00:01:46 UTC,view,5843665,1487580005092295511,NaN,f.o.x,9.44,462033176,a18e0999-61a1-4218-8f8f-61ec1d375361
1,72,2019-10-01 00:01:55 UTC,cart,5868461,1487580013069861041,NaN,italwax,3.57,514753614,e2fecb2d-22d0-df2c-c661-15da44b3ccf1
2,95,2019-10-01 00:02:50 UTC,view,5877456,1487580006300255120,NaN,jessnail,122.22,527418424,86e77869-afbc-4dff-9aa2-6b7dd8c90770

In [49]:
df['event_time'] = pd.to_datetime(df['event_time'])
df['event_time'].head()

0   2019-10-01 00:01:46+00:00
1   2019-10-01 00:01:55+00:00
2   2019-10-01 00:02:50+00:00
3   2019-10-01 00:03:41+00:00
4   2019-10-01 00:03:44+00:00
Name: event_time, dtype: datetime64[us, UTC]

In [50]:
# eliminar la columna index 
df = df.drop(columns=['index'])

In [51]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [52]:
df.columns = [
    'fecha',
    'evento',
    'producto',
    'categoria',
    'categoria_cod',
    'marca',
    'precio',
    'usuario',
    'sesion',
    ]
df

,fecha,evento,producto,categoria,categoria_cod,marca,precio,usuario,sesion
0,2019-10-01 00:01:46+00:00,view,5843665,1487580005092295511,NaN,f.o.x,9.44,462033176,a18e0999-61a1-4218-8f8f-61ec1d375361
1,2019-10-01 00:01:55+00:00,cart,5868461,1487580013069861041,NaN,italwax,3.57,514753614,e2fecb2d-22d0-df2c-c661-15da44b3ccf1
2,2019-10-01 00:02:50+00:00,view,5877456,1487580006300255120,NaN,jessnail,122.22,527418424,86e77869-afbc-4dff-9aa2-6b7dd8c90770
3,2019-10-01 00:03:41+00:00,view,5649270,1487580013749338323,NaN,concept,6.19,555448072,b5f72ceb-0730-44de-a932-d16db62390df
4,2019-10-01 00:03:44+00:00,view,18082,1487580005411062629,NaN,cnd,16.03,552006247,2d8f304b-de45-4e59-8f40-50c603843fe5
...,...,...,...,...,...,...,...,...,...
2095071,2020-02-29 23:58:49+00:00,cart,5815662,1487580006317032337,NaN,NaN,0.92,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095072,2020-02-29 23:58:57+00:00,view,5815665,1487580006317032337,NaN,NaN,0.59,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095073,2020-02-29 23:59:05+00:00,cart,5815665,1487580006317032337,NaN,NaN,0.59,147995998,5ff96629-3627-493e-a25b-5a871ec78c90
2095074,2020-02-29 23:59:28+00:00,view,5817692,1487580010872045658,NaN,NaN,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d
2095075,2020-02-29 23:59:54+00:00,view,5716351,1487580010872045658,NaN,irisk,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d

In [57]:
# analisis de nulos
df.isnull().sum()

fecha        0
evento       0
producto     0
categoria    0
precio       0
usuario      0
sesion       0
dtype: int64

In [54]:
# eliminar la columna categoria_cod y marca
df = df.drop(columns=['categoria_cod', 'marca'])

In [55]:
# eliminar los nulos del dataframe
df = df.dropna()

In [60]:
df.describe()

        producto              categoria     precio      usuario
count 2094570.00             2094570.00 2094570.00   2094570.00
mean  5487103.56 1553112489392098048.00       8.42 521077545.56
std   1300923.90  167907497920480608.00      19.14  87553855.76
min      3752.00 1487580004807082752.00     -47.62   4661182.00
25%   5724652.00 1487580005754995456.00       2.05 480613387.00
50%   5811665.00 1487580008246412288.00       4.00 553341613.00
75%   5858353.00 1487580013489291520.00       6.86 578406571.00
max   5932595.00 2242903426784559104.00     327.78 622087993.00

In [64]:
df[df.precio <= 0].shape

(20544, 7)

In [66]:
df = df[df.precio > 0]